### PR TITLE
refactor: use server side apply in mso controller

### PR DESCRIPTION
**Pull request by jan--f**
Server side apply has been in beta since kubernetes 1.16 and stable
since 1.22. It greatly reduces client complexity, since no
get-patch-update cycles are needed anymore.
Additionally server side apply allows for controllers to handle user
changes on managed resources much more easily, if that need arises in
the future.
This also adds a `GenerationChangedPredicate` to the GrafanaDataSource watch.

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

### CODE REVIEW

**Comment by jan--f** [comment]
Given that `LabelSelector` is marked as `structType=atomic` the e2e test shouldn't fail like this. Still investigating.

**Comment by sthaha** [comment]
@jan--f , thanks, we have been wanting to do this !
could you please test that modifications outside the MSO to any of the resources created are reverted as well? Perhaps we need a test for that if one doesn't exist already.

**Comment by jan--f** [comment]
I think the failing test is due to https://github.com/kubernetes/kubernetes/issues/109668

**Review by sthaha — APPROVED** [review]
super!! ❤️

**Pull request merged**
